apiVersion: container.gcp.crossplane.io/v1beta2
kind: Cluster
metadata:
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-delete-policy": "before-hook-creation"
    "helm.sh/hook-weight": "-5"
  name: {{ .Values.global.name }}-cluster
  labels:
     service: gke
     creation: {{ .Values.global.name }}-cluster
spec:
  forProvider:
    addonsConfig:
      networkPolicyConfig:
        disabled: false
    networkSelector:
       matchLabels:
           service: vpc
           creation: {{ .Values.global.name }}-vpcnetwork
    subnetworkSelector:
       matchLabels:
           service: subnetwork
           creation: {{ .Values.global.name }}-subnetwork
    location: {{ .Values.global.region }}-c
    ipAllocationPolicy:
      useIpAliases: true
    masterAuth:
      clientCertificateConfig:
        issueClientCertificate: false
    defaultMaxPodsConstraint:
       maxPodsPerNode: 110
    networkPolicy:
      enabled: false
    resourceLabels:
       owner: {{ .Values.global.name }}
  providerConfigRef:
        name: default-gcp
