apiVersion: compute.gcp.crossplane.io/v1beta1
kind: Subnetwork
metadata:
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-delete-policy": "before-hook-creation"
    "helm.sh/hook-weight": "-15"
  name: {{ .Values.global.name }}-subnetwork
  labels:
     service: subnetwork
     creation: {{ .Values.global.name }}-subnetwork
spec:
  forProvider:
    region: {{ .Values.global.region }}
    ipCidrRange:  {{ .Values.global.subnetipcidrrange }}            #"10.11.0.0/16"
    privateIpGoogleAccess: true
    networkSelector:
      matchLabels:
       service: vpc
       creation: {{ .Values.global.name }}-vpcnetwork
  providerConfigRef:
    name: default-gcp
