apiVersion: container.gcp.crossplane.io/v1beta2
kind: Cluster
metadata:
  name: {{ .Values.global.name }}
  labels:
     service: gke
     creation: {{ .Values.global.name }}
spec:
  forProvider:
    addonsConfig:
      networkPolicyConfig:
        disabled: false
    networkSelector:
       matchLabels:
           service: vpc
           creation: {{ .Values.global.name }}-vpcnetwork
    subnetworkSelector:
       matchLabels:
           service: subnetwork
           creation: {{ .Values.global.name }}-subnetwork
    location:  "{{ .Values.global.location }}" 
    ipAllocationPolicy:
      useIpAliases: true
    masterAuth:
      clientCertificateConfig:
        issueClientCertificate: false
    defaultMaxPodsConstraint:
       maxPodsPerNode: 60
    networkPolicy:
      enabled: false
    resourceLabels:
       owner: {{ .Values.global.name }}
  providerConfigRef:
        name: default-gcp
