apiVersion: v2
name: crossplane-gcp
description: A Helm chart for creating the cluster in GCP.
version: 1.0.1
appVersion: "1.0.0"
maintainers:
- email: saiteja.katabhatina@opsmx.io
  name: saitejaopsmx
