apiVersion: container.gcp.crossplane.io/v1beta2
kind: Cluster
metadata:
  name: {{Values.clustername}}   
  labels:
     service: gke
     creation: {{Values.clustername}}   
spec:
  forProvider:
    addonsConfig:
      networkPolicyConfig:
        disabled: false
    networkSelector:
       matchLabels:
           service: vpc 
           creation:{{Values.vpcname}}   
    subnetworkSelector:
       matchLabels:
           service: subnetwork
           creation: {{Values.subnetname}}   
    location: {{Values.region}}   
    ipAllocationPolicy:
      useIpAliases: true
    masterAuth:
      clientCertificateConfig:
        issueClientCertificate: false
    defaultMaxPodsConstraint:
       maxPodsPerNode: 110
    networkPolicy:
      enabled: false
    resourceLabels:
       owner: opsmx
  providerConfigRef:
        name: default-gcp
