apiVersion: compute.gcp.crossplane.io/v1beta1
kind: Network
metadata:
  name: {{Values.vpcname}}-network
  labels:
     service: vpc
     creation: {{Values.vpcname}}-network
spec:
  forProvider:
    autoCreateSubnetworks: false
    description: 'This network is created by opsmx'
    routingConfig:
      routingMode: REGIONAL
  providerConfigRef:
    name: default-gcp
